[[redirects]]
  from = "/lidar-agb"
  to = "https://doi.org/10.1016/j.jag.2022.103059"

[[redirects]]
  from = "/fia-ssm-2022"
  to = "https://lucas-johnson.github.io/fia-ssm-2022"

[[redirects]]
  from = "/larse-2022"
  to = "https://lucas-johnson.github.io/larse-2022"

[[redirects]]
  from = "/agu-2022"
  to = "https://lucas-johnson.github.io/agu-2022"
