[[redirects]]
  from = "/phd-capstone"
  to = "https://lucas-johnson.github.io/phd-capstone/slides"


[[redirects]]
  from = "/agu2023poster"
  to = "https://www.lucaskjohnson.com/presentations/agu_2023_poster.pdf"
  
[[redirects]]
  from = "agu2023poster"
  to = "https://www.lucaskjohnson.com/presentations/agu_2023_poster.pdf"

[[redirects]]
  from = "/forest-eco-2023"
  to = "https://lucas-johnson.github.io/forest-eco-fall-2023/slides"

[[redirects]]
  from = "/cv"
  to = "https://www.lucaskjohnson.com/cv.pdf"
  
  
[[redirects]]
  from = "/twitter"
  to = "https://twitter.com/lucaskjohnson03"
  
[[redirects]]
  from = "/github"
  to = "https://github.com/lucas-johnson"
  
[[redirects]]
  from = "/linkedin"
  to = "https://www.linkedin.com/in/lucaskjohnson/"
  
[[redirects]]
  from = "/researchgate"
  to = "https://www.researchgate.net/profile/Lucas-Johnson-8"

[[redirects]]
  from = "/orcid"
  to = "https://orcid.org/my-orcid?orcid=0000-0002-7953-0260"

[[redirects]]
  from = "/lidar-agb"
  to = "https://doi.org/10.1016/j.jag.2022.103059"

[[redirects]]
  from = "/fia-ssm-2022"
  to = "https://lucas-johnson.github.io/fia-ssm-2022"

[[redirects]]
  from = "/larse-2022"
  to = "https://lucas-johnson.github.io/larse-2022"

[[redirects]]
  from = "/agu-2022"
  to = "https://lucas-johnson.github.io/agu-2022"

[[redirects]]
  from = "/femc-2022"
  to = "https://lucas-johnson.github.io/femc-2022"
